#!/usr/bin/env python3
"""Build the Informatica API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Cloud Data Governance': 'Data Governance',
    'Cloud Data Profiling': 'Data Profiling',
}

LINES = [
    {
        "name": 'Informatica Platform',
        "color": '#FF7900',
        "stations": [
        ('Platform', (260, 200)),
        ('Data Integration', (430, 175)),
        ('Cloud Data Governance', (620, 165)),
        ('Cloud Data Profiling', (810, 175)),
        ],
    },
    {
        "name": 'Cloud Services',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Address Verification', (820, 480)),
        ('B2B Gateway', (910, 555)),
        ('Reference 360', (730, 555)),
        ],
    },
]

URL_OVERRIDES = {
    'Platform': 'https://apis.apis.io/apis/informatica/informatica/',
    'Data Integration': 'https://apis.apis.io/apis/informatica/data-integration-rest-api/',
    'Cloud Data Governance': 'https://apis.apis.io/apis/informatica/cloud-data-governance-and-catalog-api/',
    'Cloud Data Profiling': 'https://apis.apis.io/apis/informatica/cloud-data-profiling-rest-api/',
    'Address Verification': 'https://apis.apis.io/apis/informatica/cloud-address-verification-api/',
    'B2B Gateway': 'https://apis.apis.io/apis/informatica/b2b-gateway-rest-api/',
    'Reference 360': 'https://apis.apis.io/apis/informatica/reference-360-rest-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Informatica API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: informatica/openapi · github.com/api-evangelist/informatica',
        out_dir=Path(__file__).resolve().parent,
        out_basename='informatica-subway-map',
        provider_id='informatica',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
